name: PR Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - name: Run test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
